apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: alpaca-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      run: alpaca-prod
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: alpaca-prod
        app: alpaca
        env: prod
        ver: "1"
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-arm:blue
        name: alpaca-prod
        ports:
        - containerPort: 8080
        resources: {}

